'use client';

import { useMemo, useState } from 'react';
import { BellRing, CheckCircle2, Clock3, Filter, ShieldCheck, Sparkles } from 'lucide-react';
import { PublicSiteChrome } from '@/components/public-site-chrome';
import { changelogEntries, changelogFilters, type ChangelogCategory } from '@/data/changelog';

const categoryStyle: Record<ChangelogCategory, string> = {
  feature: 'bg-emerald-100 text-emerald-800 ring-emerald-200',
  security: 'bg-violet-100 text-violet-800 ring-violet-200',
  improvement: 'bg-sky-100 text-sky-800 ring-sky-200',
  release: 'bg-amber-100 text-amber-800 ring-amber-200',
};

export default function ChangelogPage() {
  const [activeFilter, setActiveFilter] = useState<'all' | ChangelogCategory>('all');
  const visibleEntries = useMemo(() => changelogEntries.filter((entry) => activeFilter === 'all' || entry.category === activeFilter), [activeFilter]);

  return <PublicSiteChrome active="changelog">
    <section className="overflow-hidden bg-[radial-gradient(circle_at_82%_18%,rgba(255,255,255,0.18),transparent_28%),linear-gradient(135deg,#0b5c2c,#147a5b_56%,#0f172a)] px-4 py-16 text-white sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-1.5 text-xs font-bold text-amber-300"><BellRing className="size-4" /> SYSTEM CHANGELOG</span><h1 className="mt-6 max-w-4xl text-4xl font-extrabold leading-tight sm:text-5xl">កំណត់ត្រាកំណែទម្រង់ប្រព័ន្ធ</h1><p className="mt-3 text-lg font-bold text-emerald-100">System Changelog &amp; Release Notes</p><p className="mt-6 max-w-3xl text-sm leading-8 text-emerald-50 sm:text-base">តាមដានរាល់ការវិវត្តន៍ មុខងារថ្មីៗ និងប្រព័ន្ធសុវត្ថិភាពនៃ KSIT Dormitory Management System។</p></div><aside className="rounded-3xl border border-white/15 bg-white/10 p-7 backdrop-blur-sm lg:col-span-4"><Sparkles className="size-10 text-amber-300" /><p className="mt-5 text-xs font-bold tracking-[0.16em] text-emerald-100">LATEST RELEASE</p><p className="mt-2 text-3xl font-black">{changelogEntries[0].version}</p><p className="mt-2 text-sm leading-6 text-emerald-100">{changelogEntries[0].title}</p></aside></div></section>
    <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-5 md:grid-cols-3"><article className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><Clock3 className="size-6 text-[#147a5b]" /><p className="mt-4 text-sm font-bold text-slate-700">៥ កំណែទម្រង់ចុងក្រោយ</p><p className="mt-1 text-3xl font-black text-[#147a5b]">5 Latest Updates</p></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-6"><ShieldCheck className="size-6 text-violet-700" /><p className="mt-4 text-sm font-bold text-slate-700">Security hardening</p><p className="mt-1 text-sm leading-6 text-slate-600">RBAC និង protected API authorization ត្រូវបានពង្រឹងជាបន្តបន្ទាប់។</p></article><article className="rounded-2xl border border-sky-200 bg-sky-50 p-6"><CheckCircle2 className="size-6 text-sky-700" /><p className="mt-4 text-sm font-bold text-slate-700">Production-ready workflow</p><p className="mt-1 text-sm leading-6 text-slate-600">ពី role portals រហូតដល់ mobile controls និង manual room placement។</p></article></div>
      <div className="mt-12 flex flex-col gap-5 border-b border-slate-200 pb-6 md:flex-row md:items-center md:justify-between"><div><p className="flex items-center gap-2 text-xs font-bold tracking-[0.16em] text-[#147a5b]"><Filter className="size-4" /> FILTER RELEASE NOTES</p><h2 className="mt-2 text-3xl font-extrabold text-slate-900">Timeline នៃការអភិវឌ្ឍ</h2></div><div className="flex flex-wrap gap-2" aria-label="Filter changelog entries">{changelogFilters.map((filter) => <button key={filter.key} type="button" onClick={() => setActiveFilter(filter.key)} aria-pressed={activeFilter === filter.key} className={`rounded-full border px-4 py-2 text-sm font-bold transition ${activeFilter === filter.key ? 'border-[#147a5b] bg-[#147a5b] text-white' : 'border-slate-200 bg-white text-slate-600 hover:border-emerald-300 hover:text-[#147a5b]'}`}>{filter.label}<span className="ml-1.5 text-xs opacity-80">{filter.englishLabel}</span></button>)}</div></div>
      <div className="relative mt-10 space-y-8 before:absolute before:bottom-3 before:left-4 before:top-3 before:w-px before:bg-emerald-200 md:before:left-1/2">{visibleEntries.map((entry, index) => <article key={entry.version} className={`relative grid gap-4 md:grid-cols-2 ${index % 2 === 0 ? 'md:text-right' : ''}`}><div className={`relative ${index % 2 === 0 ? 'md:col-start-1' : 'md:col-start-2'}`}><span className="absolute left-4 top-8 z-10 flex size-8 -translate-x-1/2 items-center justify-center rounded-full border-4 border-[#f8faf8] bg-[#147a5b] text-[10px] font-black text-amber-300 md:left-auto md:right-[-2.2rem]">{entry.version.replace('v', '')}</span><div className={`ml-10 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:ml-0 ${index % 2 === 0 ? 'md:mr-12' : 'md:ml-12'}`}><div className={`flex flex-wrap items-center gap-3 ${index % 2 === 0 ? 'md:justify-end' : ''}`}><span className="text-2xl font-black text-[#147a5b]">{entry.version}</span><span className={`rounded-full px-3 py-1 text-xs font-black ring-1 ${categoryStyle[entry.category]}`}>{entry.categoryLabel}</span></div><p className="mt-3 text-xs font-bold text-slate-500">{entry.dateLabel}</p><h3 className="mt-3 text-xl font-extrabold leading-snug text-slate-900">{entry.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{entry.summary}</p><ul className="mt-5 space-y-2 text-left">{entry.highlights.map((highlight) => <li key={highlight} className="flex gap-2 text-sm leading-6 text-slate-700"><CheckCircle2 className="mt-1 size-4 shrink-0 text-[#147a5b]" />{highlight}</li>)}</ul></div></div></article>)}{visibleEntries.length === 0 && <div className="relative ml-10 rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-sm text-slate-600">មិនមានកំណែទម្រង់ត្រូវនឹង filter នេះទេ។</div>}</div></div></section>
  </PublicSiteChrome>;
}

