'use client';

import Link from 'next/link';
import { ArrowRight, Building2, HeartHandshake, Leaf, Lightbulb, MapPin, Phone, School, ShieldCheck, Sparkles, Target, Users } from 'lucide-react';
import { PublicSiteChrome } from '@/components/public-site-chrome';

const missions = [
  'បណ្តុះបណ្តាលនិស្សិតថ្នាក់បរិញ្ញាបត្ររង និងបរិញ្ញាបត្រលើផ្នែកបច្ចេកវិទ្យា និងកសិកម្ម ប្រកបដោយគុណភាព និងឆ្លើយតបតាមតម្រូវការនៃការអភិវឌ្ឍសង្គម និងទីផ្សារការងារ។',
  'អភិវឌ្ឍសមត្ថភាពគណៈគ្រប់គ្រង សាស្រ្តាចារ្យ និងបុគ្គលិកប្រកបដោយនិរន្តរភាព និងស្របតាមស្តង់ដាជាតិ។',
  'អភិរក្សវប្បធម៌ បរិស្ថាន និងផ្តល់សេវាកម្មដល់សហគមន៍លើផ្នែកបច្ចេកទេសកសិកម្ម និងបច្ចេកវិទ្យា។',
];

const values = [
  { title: 'គុណភាព និងភាពលេចធ្លោ', english: 'Quality & Excellence', icon: Sparkles, tone: 'bg-emerald-50 text-[#147a5b]' },
  { title: 'គុណធម៌ និងសាមគ្គីភាព', english: 'Virtue & Solidarity', icon: HeartHandshake, tone: 'bg-amber-50 text-amber-700' },
  { title: 'នវានុវត្តន៍ និងការច្នៃប្រតិដ្ឋ', english: 'Innovation & Creativity', icon: Lightbulb, tone: 'bg-sky-50 text-sky-700' },
  { title: 'សេចក្តីសុខក្នុងការសិក្សាពេញមួយជីវិត', english: 'Lifelong Learning', icon: School, tone: 'bg-violet-50 text-violet-700' },
];

export default function AboutKSITPage() {
  return <PublicSiteChrome active="about">
    <section className="overflow-hidden bg-[radial-gradient(circle_at_85%_18%,rgba(255,255,255,0.18),transparent_28%),linear-gradient(135deg,#0b5c2c,#147a5b_56%,#0f172a)] px-4 py-16 text-white sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-12 lg:items-center"><div className="lg:col-span-8"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-1.5 text-xs font-bold text-amber-300"><School className="size-4" /> KAMPONG SPEU INSTITUTE OF TECHNOLOGY</span><h1 className="mt-6 max-w-4xl text-4xl font-extrabold leading-tight sm:text-5xl">អំពីវិទ្យាស្ថានបច្ចេកវិទ្យាកំពង់ស្ពឺ</h1><p className="mt-3 text-lg font-bold text-emerald-100">About KSIT</p><p className="mt-6 max-w-3xl text-sm leading-8 text-emerald-50 sm:text-base">គ្រឹះស្ថានឧត្តមសិក្សាសាធារណៈ ស្ថិតក្រោមឱវាទក្រសួងអប់រំ យុវជន និងកីឡា សាងសង់លើផ្ទៃដីប្រមាណ ២០០.៣ ហិចតា។</p></div><aside className="rounded-3xl border border-white/15 bg-white/10 p-7 backdrop-blur-sm lg:col-span-4"><Building2 className="size-10 text-amber-300" /><p className="mt-5 text-sm font-bold">ការសិក្សា បច្ចេកវិទ្យា និងកសិកម្ម</p><p className="mt-2 text-sm leading-6 text-emerald-100">KSIT ផ្តោតលើការអប់រំមានគុណភាព ការច្នៃប្រតិដ្ឋ និងការចូលរួមជាមួយសហគមន៍។</p></aside></div></section>
    <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-12"><div className="lg:col-span-5"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-[#147a5b]">VISION &amp; MISSION</span><h2 className="mt-4 text-3xl font-extrabold text-slate-900">ចក្ខុវិស័យ និងបេសកកម្ម</h2><p className="mt-4 text-sm leading-7 text-slate-600">ទិសដៅរបស់វិទ្យាស្ថានគឺការក្លាយជាគ្រឹះស្ថានឈានមុខគេនៅតាមបណ្តាខេត្ត លើការច្នៃប្រតិដ្ឋ និងនវានុវត្តន៍ផ្នែកបច្ចេកវិទ្យា និងកសិកម្ម ដើម្បីរួមចំណែកក្នុងការអភិវឌ្ឍសហគមន៍ និងប្រទេសជាតិប្រកបដោយនិរន្តរភាព។</p><a href="https://ksit.edu.kh/about-ksit/" target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#147a5b] hover:underline">អានព័ត៌មានផ្លូវការ KSIT <ArrowRight className="size-4" /></a></div><div className="space-y-4 lg:col-span-7"><article className="rounded-3xl border border-emerald-200 bg-emerald-50/70 p-7"><div className="flex gap-3"><Target className="mt-1 size-6 shrink-0 text-[#147a5b]" /><div><p className="text-xs font-bold tracking-[0.16em] text-[#147a5b]">VISION</p><h3 className="mt-2 text-xl font-extrabold text-slate-900">ចក្ខុវិស័យ</h3><p className="mt-3 text-sm leading-7 text-slate-700">វិទ្យាស្ថានបច្ចេកវិទ្យាកំពង់ស្ពឺជាគ្រឹះស្ថានឧត្តមសិក្សាសាធារណៈដែលឈានមុខគេនៅតាមបណ្តាខេត្ត លើការច្នៃប្រតិដ្ឋ និងនវានុវត្តន៍ផ្នែកបច្ចេកវិទ្យា និងកសិកម្ម ដើម្បីចូលរួមក្នុងការអភិវឌ្ឍសហគមន៍ និងប្រទេសជាតិប្រកបដោយនិរន្តរភាព។</p></div></div></article><article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex gap-3"><Users className="mt-1 size-6 shrink-0 text-[#147a5b]" /><div><p className="text-xs font-bold tracking-[0.16em] text-[#147a5b]">MISSION</p><h3 className="mt-2 text-xl font-extrabold text-slate-900">បេសកកម្ម</h3><ol className="mt-4 space-y-3">{missions.map((mission, index) => <li key={mission} className="flex gap-3 text-sm leading-7 text-slate-700"><span className="mt-0.5 flex size-6 shrink-0 items-center justify-center rounded-full bg-[#147a5b] text-xs font-black text-amber-300">{index + 1}</span>{mission}</li>)}</ol></div></div></article></div></div></section>
    <section className="border-y border-emerald-100 bg-emerald-50/70 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><span className="rounded-full bg-[#147a5b] px-3 py-1 text-xs font-bold text-white">GOALS &amp; CORE VALUES</span><h2 className="mt-4 text-3xl font-extrabold text-slate-900">គោលបំណង និងគុណតម្លៃស្នូល</h2><p className="mt-3 text-sm leading-7 text-slate-600">KSIT ប្តេជ្ញាបណ្តុះបណ្តាលនិស្សិតប្រកបដោយគុណភាព បង្កើតប្រព័ន្ធគ្រប់គ្រងមានប្រសិទ្ធភាព និងផ្តល់សេវាកម្មដែលមានប្រយោជន៍ដល់សហគមន៍។</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{values.map((value) => { const Icon = value.icon; return <article key={value.title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className={`flex size-11 items-center justify-center rounded-xl ${value.tone}`}><Icon className="size-5" /></div><h3 className="mt-4 text-lg font-bold text-slate-900">{value.title}</h3><p className="mt-2 text-sm text-slate-500">{value.english}</p></article>; })}</div></div></section>
    <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-12"><article className="rounded-3xl bg-[#0f6047] p-8 text-white lg:col-span-7"><Leaf className="size-10 text-amber-300" /><p className="mt-6 text-xs font-bold tracking-[0.16em] text-emerald-200">CAMPUS &amp; STUDENT RESIDENCE</p><h2 className="mt-3 text-3xl font-extrabold">បរិវេណសិក្សា កសិដ្ឋានស្រាវជ្រាវ និងការស្នាក់នៅរបស់និស្សិត</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-emerald-100">បរិវេណ KSIT មានផ្ទៃដីប្រមាណ ២០០.៣ ហិចតា ដែលគាំទ្រការសិក្សាផ្នែកបច្ចេកវិទ្យា និងកសិកម្ម រួមទាំងបរិក្ខារស្នាក់នៅសម្រាប់និស្សិត។ ប្រព័ន្ធអន្តេវាសិកដ្ឋានជួយឱ្យការដាក់ពាក្យ ការចាត់បន្ទប់ វត្តមាន និងសេវាបន្ទប់ត្រូវបានគ្រប់គ្រងដោយតម្លាភាព។</p><Link href="/login" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-amber-400 px-6 py-3.5 text-sm font-bold text-slate-950 hover:bg-amber-500">ចូលទៅកាន់ប្រព័ន្ធគ្រប់គ្រងអន្តេវាសិកដ្ឋាន <ArrowRight className="size-4" /></Link></article><article className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm lg:col-span-5"><MapPin className="size-8 text-[#147a5b]" /><p className="mt-5 text-xs font-bold tracking-[0.16em] text-[#147a5b]">OFFICIAL CONTACT</p><h2 className="mt-2 text-2xl font-extrabold text-slate-900">ព័ត៌មានទំនាក់ទំនងផ្លូវការ</h2><p className="mt-5 text-sm leading-7 text-slate-600">អាសយដ្ឋាន៖ ផ្លូវជាតិលេខ ៤៤ ភូមិអូរអង្គំ ឃុំអមលាំង ស្រុកថ្ពង ខេត្តកំពង់ស្ពឺ</p><p className="mt-4 flex gap-2 text-sm leading-6 text-slate-700"><Phone className="mt-0.5 size-4 shrink-0 text-[#147a5b]" />089 511 383 / 092 740 222 / 016 643 263 / 010 761 349</p><p className="mt-4 flex gap-2 text-sm leading-6 text-slate-700"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-[#147a5b]" />info@ksit.edu.kh</p></article></div></section>
  </PublicSiteChrome>;
}

